### ISSUE TITLE
Change Firegento Location from HTTP to HTTPS

### ISSUE THREAD

**Issue by brandontamm** [andreaskoch/dockerized-magento#11]
@andreaskoch - Composer developers made https mandatory for composer to connect to repositories:
https://github.com/composer/composer/issues/4963

  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.firegento.com"
    }

**Comment by yssource** [comment]
The same issue happens to me also.
After changing http to https, I got odd error log "The "https://packages.firegento.com/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known"
