### ISSUE TITLE
Install without Sample Data?

### ISSUE THREAD

**Issue by brandontamm** [andreaskoch/dockerized-magento#13]
Anyone know which lines to remove/include from the installer shell script to still automate the installation but start with a fresh clean database (instead of sample data?)

**Comment by riker09** [comment]
Yes, see file `docker-images/installer/bin/install.sh`, lines 103-106:

```
[...]

echo "Installing Sample Data: Media"
curl -s -L https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/1.9.1.0/compressed-no-mp3-magento-sample-data-1.9.1.0.tgz | tar xz -C /tmp
cp -av /tmp/magento-sample-data-*/* $MAGENTO_ROOT
rm -rf /tmp/magento-sample-data-*

[...]
```

**Comment by brandontamm** [comment]
I wish it were that easy to just remove that block of code but its not quite that simple :)

I actually accomplished this by using magerun to install a fresh database and that worked perfectly and some functions.

First, remove the following blocks of code from ./docker-images/installer/bin/install.sh:

* echo "Installing Sample Data: Media"
* echo "Installing Sample Data: Database"
* echo "Installing Sample Data: Reindex"
* echo "Installing Sample Data: Admin User"

Then, take a look at this diff (if anyone wants the code or uses this I'll create a pull request:)
![screen shot 2016-09-09 at 9 00 49 am](https://cloud.githubusercontent.com/assets/1854016/18389535/fd519f38-766b-11e6-87bc-58fa0d3642a1.png)

**Comment by brandontamm** [comment]
So I needed a function to wait for MYSQL and then I used Magerun to automate Magento installation with the docker-compose.yml variables:

echo "Starting Installation"
mysqlWait
magerun --skip-root-check --root-dir="$MAGENTO_ROOT" install --noDownload --dbHost="$MYSQL_HOST" --dbUser="$MYSQL_USER" --dbPass="$MYSQL_PASSWORD" --dbName="$MYSQL_DATABASE" --installSampleData="no" --useDefaultConfigParams="yes" --installationFolder="$MAGENTO_ROOT" --baseUrl="http://$DOMAIN"

**Comment by andreaskoch** [comment]
Hi @brandontamm,
for now I don't think I will add this option to this project since it was made to create a quick start for a dockerized Magento 1.

But I will create a new project which works similar to my [dockerize-magento2](https://github.com/arvatoSCM/dockerize-magento2) project which will not include sample data.

Once that's ready I will reference it here.
