### ISSUE TITLE
403 Forever..

### ISSUE THREAD

**Issue by lodestream** [andreaskoch/dockerized-magento#15]
Or 500(/index.php/), whatever the page is, cannot load the website from another computer.

I set this up on my cloud server, and accessing the website from my local computer.

**Comment by youdarcd** [comment]
![qq20160619-0 2x](https://cloud.githubusercontent.com/assets/19382441/16176906/0b87ca1c-364f-11e6-86b5-91a60ad36468.png)

I'm wondering why, I can't understand the nginx part neither. I cd to that directory `/var/www/html/web`, there is nothing but a media and skin folder.

**Comment by usbportnoy** [comment]
Im experiencing the same issue

**Comment by mattythebatty** [comment]
Its because the composer install of magento doesn't work properly.

> Problem 1
>     - magento-hackathon/magento-composer-installer 2.1.1 requires composer-plugin-api 1.0.0 -> no matching package found.
>     - magento-hackathon/magento-composer-installer 2.1.1 requires composer-plugin-api 1.0.0 -> no matching package found.
>     - Installation request for magento-hackathon/magento-composer-installer v2.1.1 -> satisfiable by magento-hackathon/magento-composer-installer[2.1.1].

**Comment by mattythebatty** [comment]
Got it working!

I changed the composer.json file to this: 
[composer.txt](https://github.com/andreaskoch/dockerized-magento/files/346801/composer.txt)

I'm not sure if all the changes I made were necessary so I haven't included it in PR but it might be worth @andreaskoch having a look?

**Comment by dm-wyncode** [comment]
@all9lives you saved my one life. Thank you for the fix!!!

**Comment by Suseika** [comment]
@andreaskoch Please merge the commit referenced in this issue into your repository.

**Comment by riker09** [comment]
@andreaskoch @Suseika I've created a pull request to make the maintainers life a little less difficult. :)

**Comment by andreaskoch** [comment]
Hi everybody.
Sorry I respond so slowly to your issues. The issue should be resolved with version ≥ v0.10.0

Greetings
 Andy
