### ISSUE TITLE
 ERROR: for nginx  driver failed programming external connectivity on endpoint 

### ISSUE THREAD

**Issue by caneraydinbey** [andreaskoch/dockerized-magento#19]
WARNING: Image for service installer was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating dockerizedmagento_mysql_1
Creating dockerizedmagento_fullpagecache_1
Creating dockerizedmagento_sessions_1
Creating dockerizedmagento_cache_1
Creating dockerizedmagento_solr_1
Creating dockerizedmagento_php_1
Creating dockerizedmagento_nginx_1

ERROR: for nginx  driver failed programming external connectivity on endpoint dockerizedmagento_nginx_1 (f4231c1e80b680a8a59961cb3658c55d2b64cc3a3e980e09f8b94531a608892f): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
**caner@vegan:~**/magento-caner/dockerized-magento$ ./magento start
dockerizedmagento_fullpagecache_1 is up-to-date
dockerizedmagento_solr_1 is up-to-date
dockerizedmagento_mysql_1 is up-to-date
dockerizedmagento_sessions_1 is up-to-date
dockerizedmagento_cache_1 is up-to-date
dockerizedmagento_php_1 is up-to-date
Starting dockerizedmagento_nginx_1

ERROR: for nginx  driver failed programming external connectivity on endpoint dockerizedmagento_nginx_1 (3e4887cb50ff899b19f660d3886f03d6682cf6332373912c0aa9e3932f4d8e5c): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
**caner@vegan:~**/magento-caner/dockerized-magento$ 

after a whihle, the error is when i open the page

> 403 Forbidden
> 
> nginx/1.11.3

which are given from console : 

> installer_1      | 
> installer_1      | Fixing filesystem permissions
> installer_1      | Installation fininished
> installer_1      | Frontend: http://dockerized-magento.local/
> installer_1      | Backend: http://dockerized-magento.local/admin
> installer_1      |  - Username: admin
> installer_1      |  - Password: password123

images are

> fabf508632a6        dockerizedmagentomaster_installer   "/bin/install.sh"        4 minutes ago       Up 4 minutes                                                   dockerizedmagentomaster_installer_1
> 44a8db375577        nginx:latest                        "nginx -g 'daemon off"   4 minutes ago       Up 4 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   dockerizedmagentomaster_nginx_1
> 73883d1ad863        dockerizedmagentomaster_php         "php-fpm"                4 minutes ago       Up 4 minutes        9000/tcp                                   dockerizedmagentomaster_php_1
> 6c7e24a5f1b6        dockerizedmagentomaster_solr        "/usr/bin/java -Xmx10"   4 minutes ago       Up 4 minutes        8983/tcp                                   dockerizedmagentomaster_solr_1
> 824765d3e79d        mysql:5.5                           "docker-entrypoint.sh"   4 minutes ago       Up 4 minutes        0.0.0.0:3306->3306/tcp                     dockerizedmagentomaster_mysql_1
> 515fde576688        redis:latest                        "docker-entrypoint.sh"   28 minutes ago      Up 4 minutes        6379/tcp                                   dockerizedmagentomaster_sessions_1
> e6a583fda276        redis:latest                        "docker-entrypoint.sh"   28 minutes ago      Up 4 minutes        6379/tcp                                   dockerizedmagentomaster_cache_1
> e449459d1355        redis:latest                        "docker-entrypoint.sh"   28 minutes ago      Up 4 minutes        6379/tcp                                   dockerizedmagentomaster_fullpagecache_1

Also

>    [RuntimeException]  
> installer_1      |   Magento folder could not be detected  
> installer_1      |

**Comment by andreaskoch** [comment]
Hi @caneraydinbey.
The project was in a bad shape a few month ago because it hasn't been updated in a while.
Since then I have create a newer version which should work again.

Please clone the project in a different folder and try again.

Greetings
 Andy
