### ISSUE TITLE
Basic installation php error

### ISSUE THREAD

**Issue by caneraydinbey** [andreaskoch/dockerized-magento#20]
When i try to install from here https://github.com/andreaskoch/dockerized-magento

the errors are

> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> 
> creating libtool
> appending configuration tag "CXX" to libtool
> configure: creating ./config.status
> config.status: creating config.h
> - docker-php-ext-install
>   usage: /usr/local/bin/docker-php-ext-install [-jN] ext-name [ext-name ...]
>   ie: /usr/local/bin/docker-php-ext-install gd mysqli
>      /usr/local/bin/docker-php-ext-install pdo pdo_mysql
>      /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop
> 
> if custom ./configure arguments are necessary, see docker-php-ext-configure
> 
> Possible values for ext-name:
> bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mcrypt mssql mysql mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets spl standard sybase_ct sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip
> ERROR: Service 'php' failed to build: The command '/bin/sh -c buildDeps="       libpng12-dev       libjpeg-dev       libmcrypt-dev       libxml2-dev       freetype\* "; set -x && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/\* && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr --with-freetype-dir && docker-php-ext-install' returned a non-zero code: 1

**Comment by andreaskoch** [comment]
The PHP takes forever and sometimes breaks. I have switch to a pre-built php container a while ago (see: 09b0005c1558c2f2491e9dc7ed51b777e7d79850)

Can you please try again? If the error persists please reopen the issue.
