### ISSUE TITLE
windows 10 nignix issue

### ISSUE THREAD

**Issue by sivajik34** [andreaskoch/dockerized-magento#22]
ERROR: for nginx  Cannot start service nginx: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/fb29dddc04468de8c4432f53e09a4ddfa7c45a4d380b91f09aa2ce6bce0db00f/etc/nginx/nginx.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/fb29dddc04468de8c4432f53e09a4ddfa7c45a4d380b91f09aa2ce6bce0db00f" caused "not a directory"
[31mERROR[0m: Encountered errors while bringing up the project.

Admin@DESKTOP-O87GU72 MINGW64 ~/m9docker/dockerized-magento (master)
$ docker-compose up
dockerizedmagento_cache_1 is up-to-date
dockerizedmagento_fullpagecache_1 is up-to-date
dockerizedmagento_mysql_1 is up-to-date
dockerizedmagento_sessions_1 is up-to-date
dockerizedmagento_solr_1 is up-to-date
dockerizedmagento_php_1 is up-to-date
Starting dockerizedmagento_nginx_1

ERROR: for nginx  Cannot start service nginx: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/fb29dddc04468de8c4432f53e09a4ddfa7c45a4d380b91f09aa2ce6bce0db00f/etc/nginx/nginx.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/fb29dddc04468de8c4432f53e09a4ddfa7c45a4d380b91f09aa2ce6bce0db00f" caused "not a directory"
[31mERROR[0m: Encountered errors while bringing up the project.

Admin@DESKTOP-O87GU72 MINGW64 ~/m9docker/dockerized-magento (master)
$

**Comment by at10ti0n** [comment]
sharing the C: drive in docker Shared Drives settings helped me move past this issue

**Comment by andreaskoch** [comment]
Hej @sivajik34,
using docker on Windows is usually a tricky thing because of the file sharing between Windows and the Docker VM. Especially when it comes to Magento with all of it's files and potentially symlinks.

I will upgrade the project to docker-compose version 2 and maybe this will work better then.
