### ISSUE TITLE
nginx issue in windows 10

### ISSUE THREAD

**Issue by sivajik34** [andreaskoch/dockerized-magento#24]
Creating dockerizedmagento_solr_1
Creating dockerizedmagento_fullpagecache_1
Creating dockerizedmagento_sessions_1
Creating dockerizedmagento_cache_1
Creating dockerizedmagento_mysql_1
Creating dockerizedmagento_php_1
Creating dockerizedmagento_nginx_1

ERROR: for nginx  Cannot start service nginx: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/6dc10df5fa48c5d8753491fe169d0e25d2b7eb109b8870a44cac784fadf573e0/etc/nginx/nginx.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/6dc10df5fa48c5d8753491fe169d0e25d2b7eb109b8870a44cac784fadf573e0" caused "not a directory"
[31mERROR[0m: Encountered errors while bringing up the project.

**Comment by andreaskoch** [comment]
I would say this is related to #22.

Docker and Windows is tricky and I will not be able to help you with that.
