### ISSUE TITLE
403 Fobidden

### ISSUE THREAD

**Issue by marcoblg** [andreaskoch/dockerized-magento#25]
Hello,
I just set up your docker-compose.yml but when I try to access to Magento the browser show the 403 Forbidden message of ngnx. In the error.log there are the following errors:

[error] 7#7: *3 directory index of "/var/www/html/web/" is forbidden, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", host: "dockerized-magento.local"
[error] 7#7: *3 open() "/var/www/html/web/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "dockerized-magento.local", referrer: "http://dockerized-magento.local/"

Any idea?
Thank you
Marco

**Comment by marcoblg** [comment]
Could the following script, in Magento file, be the reason of the issue? 

In the executeMagerun() I have root-dir="/var/www/html/web"
while 
in the executeComposer() I have working-dir="/var/www/html"

executeMagerun() {
    local containerType="installer"
    local containerName=$(getContainerNameByType "$containerType")
    if [ -z "$containerName" ];
    then
        echo "Cannot determine the name of the container." >&2
        return 1
    fi

    $DOCKER exec -ti $containerName magerun --skip-root-check --root-dir="/var/www/html/web" $@
    return 0
}

executeComposer() {
    local containerType="installer"
    local containerName=$(getContainerNameByType $containerType)
    if [ -z "$containerName" ];
    then
        echo "Cannot determine the name of the container." >&2
        return 1
    fi

    $DOCKER exec $containerName composer --working-dir="/var/www/html" $@
    return 0
}

**Comment by marcoblg** [comment]
Sorry I found another reference to to the path /web
![path](https://cloud.githubusercontent.com/assets/22501564/18945425/70b0567a-8622-11e6-9c50-943ab6cbb2de.png)

**Comment by timrsfo** [comment]
were you able to solve this problem? how?
I have a similar issue but via a different path, no luck solving it.

**Comment by andreaskoch** [comment]
Hi @marcoblg.
This issue should be resolved by in all version ≥ v0.10.0. Could create fresh clone and try again?
If you are still experiencing this issue or create a new one.

Greetings
 Andy
