### ISSUE TITLE
NGINX Config

### ISSUE THREAD

**Issue by brandontamm** [andreaskoch/dockerized-magento#26]
Can you share which location we should be using to make changes to Nginx config files - /config/nginx or /docker-images/nginx ? 

I wasn't able to figure out which set of config files were being after examining code (newbie :)

**Comment by andreaskoch** [comment]
Hi @brandontamm,
the place for changes related to Nginx configuration files should be `config/nginx`.

The `/docker-images` folder contains customized docker image definitions, but not the runtime configurations for these images.

Greetings
 Andy
