### ISSUE TITLE
Admin Panel > System>MagentoConnect > Magento Connect Manager > 403

### ISSUE THREAD

**Issue by timrsfo** [andreaskoch/dockerized-magento#29]
Magento Connect Manager throws 403 Forbidden

How do I get past this 403?

logs/access.log
`172.17.0.1 - - [04/Nov/2016:07:28:37 +0000] "GET /index.php/admin/extension_local/index/key/8c1406415afa6475579d2a7c2b4f9c19/ HTTP/1.1" 302 5 "http://dockerized-magento.local/index.php/admin/dashboard/index/key/541772674d54782a3ea990343e5ce075/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0" "-"
172.17.0.1 - - [04/Nov/2016:07:28:37 +0000] "GET /downloader/?return=http%3A%2F%2Fdockerized-magento.local%2Findex.php%2Fadmin%2F HTTP/1.1" 403 169 "http://dockerized-magento.local/index.php/admin/dashboard/index/key/541772674d54782a3ea990343e5ce075/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0" "-"`

logs/error.log
`  
 2016/11/04 07:28:37 [error] 7#7: *12 access forbidden by rule, client: 172.17.0.1, server: , request: "GET /downloader/?return=http%3A%2F%2Fdockerized-magento.local%2Findex.php%2Fadmin%2F HTTP/1.1", host: "dockerized-magento.local", referrer: "http://dockerized-magento.local/index.php/admin/dashboard/index/key/541772674d54782a3ea990343e5ce075/"
`

**Comment by timrsfo** [comment]
has anybody gotten magento connect manager to work with dockerized-magento? if so can you please tell me now - thanks

**Comment by sanvisimo** [comment]
I use this repository to build my magento docker container and it works.
You can find it in my repository

**Comment by timrsfo** [comment]
@sanvisimo when you say it works, have you done System > Magento Connect > Magento Connect Manager ? I have been using this dockerized-magento for a couple of months, only the demo site. I am able to do a lot of things with it, including RestFul API, oauth ... just fine. This is the first thing I am having trouble with.

**Comment by sanvisimo** [comment]
yes.
and installed somes modules too.
It's a permission problem with nginx, but I used the official php-apache image.
I know that must fix permission on nginx config file, I tried to do it, but I never used nginx so I skip to apache.

**Comment by timrsfo** [comment]
@sanvisimo thanks, just to be clear you got a version of dockerized-matgento to work but not this version. you had the same / similar permission problems I am having and decided to swap out nginx for apache. it seems strange that @andreaskoch wouldn't have run into this problem. i opened up this issue  [Magento Connect Manager not working with dockerized-magento](http://magento.stackexchange.com/questions/144624/magento-connect-manager-not-working-with-dockerized-magento)

**Comment by andreaskoch** [comment]
Hi @timrsfo,
I get the same error when trying to open the Magento Connect Manager.

The reason for the error is simply that I disabled that route in the Nginx config (see: [config/nginx/sites-enabled/default.conf#L31](https://github.com/andreaskoch/dockerized-magento/blob/master/config/nginx/sites-enabled/default.conf#L31)):

```
server {
    ...
    
    location ^~ /downloader/  { deny all; }
    ...

}
```

Because I never used the Connect Manager to install extensions I never thought about it that some people might want to use it.

Give me a few minutes and I will allow accessing the `/downloader` route in the Nginx config.

**Comment by andreaskoch** [comment]
Hi @timrsfo,
the Magento Connect Manger should be accessible now:

![screenshot-2016-11-09-001-magento downloader - google chrome](https://cloud.githubusercontent.com/assets/247364/20151567/d9d192be-a6ba-11e6-9898-86bf9c3a10eb.png)

If it still does not work for you feel free to re-open this issue.

Thanks for raising this issue.

Greetings
 Andy

**Comment by timrsfo** [comment]
@andreaskoch , thanks that did it!
I  tried allowing a specific IP, but that wasn't quite right.
`location ^~ /downloader/                { allow 172.17.0.1; deny all; }` ,
also see: [Configuring nginx for Magento 1.x](https://magento2.atlassian.net/wiki/display/m1wiki/Configuring+nginx+for+Magento+1.xl)

**Comment by andreaskoch** [comment]
Yeah, IP restrictions and docker are a tricky thing. You never can be sure which IP reaches the web server :-)
