### ISSUE TITLE
503 Error - Admin Panel

### ISSUE THREAD

**Issue by filipenasc** [andreaskoch/dockerized-magento#30]
I was using `dockerized-magento` normally, without any problem, but yesterday I updated my local repo, running `git pull`. So I performed `./magento destroy` in order to destroy all the containers, and after, I performed `./magento start` and `docker-compose up` again.

From there, the following error started to happens every time I login to admin panel:

```
a:5:{i:0;s:698:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sales_bestsellers_aggregated_yearly.product_type_id' in 'field list', query was: SELECT COUNT(*) FROM (SELECT MAX(DATE_FORMAT(period, '%Y-%m-%d')) AS `period`, SUM(qty_ordered) AS `qty_ordered`, `sales_bestsellers_aggregated_yearly`.`product_id`, MAX(product_name) AS `product_name`, MAX(product_price) AS `product_price`, `sales_bestsellers_aggregated_yearly`.`product_type_id` FROM `sales_bestsellers_aggregated_yearly` WHERE (EXISTS (SELECT 1 FROM `catalog_product_entity` AS `existed_products` WHERE (sales_bestsellers_aggregated_yearly.product_id = existed_products.entity_id))) AND (store_id IN(0)) GROUP BY `product_id` LIMIT 5) AS `t`";i:1;s:4693:"#0 /var/www/html/web/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
```

Does anyone having the same trouble? :confused:

**Comment by BrocksiNet** [comment]
That's a core bug ... you have to wait untill magento release the new version (i think 1.9.3.1) ... or you downgrade to magento 1.9.2.4. Greetings.

You can change in composer.json the magento core version to 1.9.2.4 and then do composer update.

**Comment by cgaugel** [comment]
Thanks, downgrade worked for me!

**Comment by filipenasc** [comment]
@bjoern-flagbit thanks! :smiley:
