### ISSUE TITLE
Magento Enterprise 1.14

### ISSUE THREAD

**Issue by brandontamm** [andreaskoch/dockerized-magento#4]
I am so close! I figured out how to configure the comnposer.json file (below) to grab my repo, but composer is installing it into the vendor directory instead of the web directory. I assume the "extra" section of the composer.json file worked with the magento/core repo but it isn't working with mine. Any ideas?

{
  "name": "",
  "description": "",
  "license": "BSD-3-Clause",
  "homepage": "",
  "require": {
    "aoepeople/aoe_scheduler": "v0.4.3",
    "aschroder/smtp_pro": "v2.0.5",
    "gordonlesti/lesti_fpc": "1.3.6",
    "jeroenvermeulen/solarium": "v1.6.9-beta",
    "magento-hackathon/magento-composer-installer": "v2.1.1",
    "brandontamm/magento-core": "1.14"
  },
  "require-dev": {
    "aoepeople/aoe_profiler": "v0.3.0",
    "aoepeople/aoe_templatehints": "v0.4.1",
    "avstudnitz/scopehint": "dev-master#9fd3eb0978fa67b55f5756494569746119f3f2f6",
    "tim-reynolds/magento-qconfig": "1.0"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "http://packages.firegento.com"
    },
    {
      "type":"package",
      "package": {
        "name": "brandontamm/magento-core",
        "version":"1.14",
        "source": {
            "url": "https://github.com/brandontamm/magento-core.git",
            "type": "git",
            "reference":"1.14"
          }
      }
  }

  ],
  "extra": {
    "magento-root-dir": "web",
    "auto-append-gitignore": true
  },
  "config": {
    "discard-changes": true
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
    "post-install-cmd": [
    ],
    "post-update-cmd": [
    ]
  }
}

**Comment by brandontamm** [comment]
I am so close! I figured out how to configure the comnposer.json file (below) to grab my repo, but composer is installing it into the vendor directory instead of the web directory. I assume the "extra" section of the composer.json file worked with the magento/core repo but it isn't working with mine. Any ideas?

{
  "name": "",
  "description": "",
  "license": "BSD-3-Clause",
  "homepage": "",
  "require": {
    "aoepeople/aoe_scheduler": "v0.4.3",
    "aschroder/smtp_pro": "v2.0.5",
    "gordonlesti/lesti_fpc": "1.3.6",
    "jeroenvermeulen/solarium": "v1.6.9-beta",
    "magento-hackathon/magento-composer-installer": "v2.1.1",
    "brandontamm/magento-core": "1.14"
  },
  "require-dev": {
    "aoepeople/aoe_profiler": "v0.3.0",
    "aoepeople/aoe_templatehints": "v0.4.1",
    "avstudnitz/scopehint": "dev-master#9fd3eb0978fa67b55f5756494569746119f3f2f6",
    "tim-reynolds/magento-qconfig": "1.0"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "http://packages.firegento.com"
    },
    {
      "type":"package",
      "package": {
        "name": "brandontamm/magento-core",
        "version":"1.14",
        "source": {
            "url": "https://github.com/brandontamm/magento-core.git",
            "type": "git",
            "reference":"1.14"
          }
      }
  }

  ],
  "extra": {
    "magento-root-dir": "web",
    "auto-append-gitignore": true
  },
  "config": {
    "discard-changes": true
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
    "post-install-cmd": [
    ],
    "post-update-cmd": [
    ]
  }
}

**Comment by brandontamm** [comment]
Hey - thank you again for providing such an awesome example Andreas!. I got this project working with Magento Enterprise 1.14. I will be cleaning up the composer.json and moving Magento core  to a private repo sometime next week. 

Would you want me to submit a pull request for the composer.json and install.sh files to swap out ce for ee using environment variables?

PS - I am still new to docker so I'd definitely be interested in learning more or reading an article about your development and deployment workflows :)

Cheers!

**Comment by andreaskoch** [comment]
Hi Brandon.
I'm happy to hear that the project helped you and that you could adapt it for Magento Enterprise Edition.

I am not sure if the Enterprise Edition changes are "generic" enough for other people, because I suspect that the majority of Magento developers won't have access to an Enterprise Edition of Magento. But maybe I am wrong. If you like create a pull request and I will have a look at your changes.

You will find all my docker-related posts at [andykdocs.de/development/Docker](https://andykdocs.de/development/Docker). My latest post is about [controlling the docker containers of this project from Minecraft](https://andykdocs.de/development/Docker/Magecraft+-+Controlling+Magento+Infrastructure+from+Minecraft):

![Magecraft - Controlling the dockerized Magento containers from Minecraft](https://cloud.githubusercontent.com/assets/247364/11453302/d8650fe4-9605-11e5-9865-7beb1314632e.gif)

... and I promise there will be more useful posts in the future ;-)

Greetings
Andy

**Comment by brandontamm** [comment]
Thanks Andy!

I do have one question that I couldn't figure out .. My first attempt failed but ended up creating a 'persistent' folder which I do not have in my second attempt (which I call a success but maybe not if that folder is supposed to be there..)

Also - what type of deployment strategy do you use to deploy code changes to Magento?
