### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by brandontamm** [andreaskoch/dockerized-magento#5]
"./magento composer update" does not work, since composer is looking in the root directory of Magento for the .json file. Would it work to remove the "/web/" from the hard-coded directory in the magento wrapper script? Other ideas?

EDIT - Removing the hard-coded "/web/" from the magento script worked :)

**Comment by andreaskoch** [comment]
Sorry for the late answer. I have fixed the issue using your proposed solution.
Thanks!
